### ISSUE TITLE
Object naming convention

### ISSUE THREAD

**Issue by soniamitchell** [IBAHCM/RPiR#8]
I'd like to replace dots in object names with underscores

http://adv-r.had.co.nz/Style.html

**Comment by richardreeve** [comment]
I have gone back and forth about this over the years. I absolutely agree with avoiding dots in function names, because `func.dataframe()` has a meaning in base R. However, I've had a lot of problems over the years with trying to eliminate dots from variable names in general because they are so pervasive and it was confusing people. In fact, the style guide doesn't call these *bad*, they just don't come under *good*. As a result we actually reverted the course from insisting on underscores everywhere to just using underscores for function names a couple of years ago. I think linking to the style guide is a good idea though!

**Comment by soniamitchell** [comment]
I do prefer the look of dots myself.. but now use underscores, even though you have to press shift! I guess it's not really important for the purpose of this course anyway.

**Comment by richardreeve** [comment]
I think it's definitely worth mentioning, but we'll only insist on it for function names.
