### ISSUE TITLE
1-6 Report - Where is 0100-example-notebook.r ?

### ISSUE THREAD

**Issue by soniamitchell** [IBAHCM/RPiR#9]

**Comment by soniamitchell** [comment]
I'll add some links / descriptions to the text

**Comment by richardreeve** [comment]
I was wondering whether to move 2-1 to 1-6 for next year, so that they have example code for the whole of the first practical series at the end of it... I've also included what is now `0200-example-notebook.R` in the Moodle files associated with practical series 2. If we put it all in 1-6, we could add the example R script here (in `practical_series_one()`, and get them to edit a simplified 1-6 report into a prettier one using hints from the example file.

**Comment by soniamitchell** [comment]
That's a good idea. I agree with moving 2-1 to 1-6. Are you suggesting 2-1 be an rmarkdown focused Practical (making 1-6 prettier)? Because that sounds perfect!

**Comment by richardreeve** [comment]
I was suggesting making 1-6 that prettifying exercise, but we could make it 1-7. I'd prefer 2-2 to become 2-1 again so that the second series is all epidemiology.

**Comment by soniamitchell** [comment]
Sounds good!

**Comment by soniamitchell** [comment]
done
